#numPy is numerical Python, it supports ndArray (n>=2  ndArray)
#We work with numerical data,All elements in an array is of similar type, i.e. homgeneous in nature

In [1]:
import numpy as np

In [2]:
#One Dim array
ar1=np.arange(10).reshape(10)

In [3]:
print(ar1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#Two Dim array  nXm array, where n=3 and m=4
ar2=np.arange(12).reshape(3,4)

In [5]:
print(ar2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#Attributes of Array

In [7]:
#What is shape of the Array (n X m)
print(ar2.shape)

(3, 4)


In [8]:
#Dim of the Array
print(ar2.ndim)

2


In [9]:
#Data Type of the array
print(ar2.dtype.name)

int32


In [10]:
#It needs 4 bytes of space
print(ar2.itemsize)

4


In [11]:
print(type(ar2))

<class 'numpy.ndarray'>


In [13]:
ar10k=np.arange(10000).reshape(1000,10)

In [14]:
print(ar10k)

[[   0    1    2 ...    7    8    9]
 [  10   11   12 ...   17   18   19]
 [  20   21   22 ...   27   28   29]
 ...
 [9970 9971 9972 ... 9977 9978 9979]
 [9980 9981 9982 ... 9987 9988 9989]
 [9990 9991 9992 ... 9997 9998 9999]]


In [15]:
ar10k1=np.arange(10000).reshape(10,1000)

In [16]:
print(ar10k1)

[[   0    1    2 ...  997  998  999]
 [1000 1001 1002 ... 1997 1998 1999]
 [2000 2001 2002 ... 2997 2998 2999]
 ...
 [7000 7001 7002 ... 7997 7998 7999]
 [8000 8001 8002 ... 8997 8998 8999]
 [9000 9001 9002 ... 9997 9998 9999]]


In [28]:
#creating another Array by assigning values directly
b=np.array([10,20.45,30])

In [27]:
print(b)

[10 20 30]


In [29]:
print(b.dtype.name)

float64


In [30]:
print(b.itemsize)

8


In [31]:
print(b.ndim)

1


In [32]:
b2d=np.array([(1,3,5),(2,3,5)])

In [33]:
print(b2d)

[[1 3 5]
 [2 3 5]]


In [34]:
print(b2d.ndim)

2


In [35]:
#Suppose we want to make all elements of the array to be double!
b2d*=2

In [36]:
print(b2d)

[[ 2  6 10]
 [ 4  6 10]]


In [37]:
myar1=np.array([(1,2,3),(4,5,6)])
myar2=np.array([(10,20,30),(40,50,60)])
myar3=myar1+myar2

In [38]:
print(myar3)

[[11 22 33]
 [44 55 66]]


<div>
    <font face=verdana size=5 color=red>
Array Creation (by zeros, ones, empty)
    </font>

In [42]:
import numpy as np
ze=np.zeros((4,5))

In [43]:
print(ze)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [44]:
one=np.ones((3,5))

In [45]:
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
empty=np.empty((2,4))

In [48]:
print(empty)

[[6.76869935e-322 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.94463125e-321 2.33645657e-307 6.23040373e-307]]


<DIV>
<font face=verdana size=5 color=orange>
Basic Operations of ndArray
</font>
</DIV>

In [49]:
a=np.array([10,20,30,40])

In [51]:
b=np.arange(4)

In [52]:
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


In [53]:
c=a-b
print(c)

[10 19 28 37]


In [54]:
c=a+b
print(c)

[10 21 32 43]


In [55]:
asqr=a**2
print(asqr)

[ 100  400  900 1600]


In [57]:
print(a<35)

[ True  True  True False]


In [ ]:
# ask the user number of elements and n and m for dimension and create an array.
#Also check that user has entered valid number.